# Generated by Django 4.2.7 on 2025-07-24 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo_name', models.CharField(help_text='IPO display name', max_length=255)),
                ('ipo_type', models.CharField(choices=[('fresh', 'Fresh Issue'), ('offer_for_sale', 'Offer for Sale'), ('mixed', 'Mixed (Fresh + OFS)')], default='fresh', max_length=20)),
                ('price_band_min', models.DecimalField(decimal_places=2, help_text='Minimum price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_band_max', models.DecimalField(decimal_places=2, help_text='Maximum price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('lot_size', models.PositiveIntegerField(help_text='Minimum number of shares per application', validators=[django.core.validators.MinValueValidator(1)])),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Total issue size in crores', max_digits=15)),
                ('fresh_issue_size', models.DecimalField(blank=True, decimal_places=2, help_text='Fresh issue size in crores', max_digits=15, null=True)),
                ('ofs_size', models.DecimalField(blank=True, decimal_places=2, help_text='Offer for Sale size in crores', max_digits=15, null=True)),
                ('ipo_open_date', models.DateField()),
                ('ipo_close_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('allotment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('listed', 'Listed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('subscription_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overall subscription rate (times)', max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual listing price', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True, help_text='Use of funds')),
                ('registrar', models.CharField(blank=True, max_length=255)),
                ('lead_managers', models.TextField(blank=True, help_text='Comma-separated list')),
                ('risk_factors', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='companies.company')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'db_table': 'ipos',
                'ordering': ['-ipo_open_date'],
            },
        ),
        migrations.CreateModel(
            name='IPOTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('announcement', 'IPO Announcement'), ('drhp_filed', 'DRHP Filed'), ('rhp_filed', 'RHP Filed'), ('price_band', 'Price Band Announced'), ('open', 'IPO Opens'), ('close', 'IPO Closes'), ('allotment', 'Allotment Finalized'), ('listing', 'Stock Listed'), ('refund', 'Refund Initiated')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='ipos.ipo')),
            ],
            options={
                'verbose_name': 'IPO Timeline',
                'verbose_name_plural': 'IPO Timelines',
                'db_table': 'ipo_timeline',
                'ordering': ['event_date'],
                'unique_together': {('ipo', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='IPOSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('retail', 'Retail Individual Investors (RII)'), ('nii', 'Non-Institutional Investors (NII)'), ('qib', 'Qualified Institutional Buyers (QIB)'), ('employee', 'Employee'), ('shareholder', 'Shareholder')], max_length=20)),
                ('shares_offered', models.BigIntegerField(help_text='Number of shares offered')),
                ('shares_applied', models.BigIntegerField(help_text='Number of shares applied for')),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('subscription_rate', models.DecimalField(decimal_places=2, help_text='Subscription rate (times)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ipos.ipo')),
            ],
            options={
                'verbose_name': 'IPO Subscription',
                'verbose_name_plural': 'IPO Subscriptions',
                'db_table': 'ipo_subscriptions',
                'unique_together': {('ipo', 'category')},
            },
        ),
    ]
