# Generated by Django 4.2.7 on 2025-07-24 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('energy', 'Energy'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('telecommunications', 'Telecommunications'), ('real_estate', 'Real Estate'), ('automotive', 'Automotive'), ('pharmaceuticals', 'Pharmaceuticals'), ('food_beverage', 'Food & Beverage'), ('textiles', 'Textiles'), ('chemicals', 'Chemicals'), ('infrastructure', 'Infrastructure'), ('media', 'Media & Entertainment'), ('other', 'Other')], max_length=50)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)])),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('cin', models.CharField(help_text='Corporate Identification Number', max_length=21, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid CIN number', regex='^[A-Z]{1}[0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$')])),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market capitalization in crores', max_digits=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('ceo_name', models.CharField(blank=True, max_length=255)),
                ('cfo_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g., 2023-2024', max_length=9)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_on_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Financial',
                'verbose_name_plural': 'Company Financials',
                'db_table': 'company_financials',
                'ordering': ['-financial_year'],
                'unique_together': {('company', 'financial_year')},
            },
        ),
    ]
