# Generated by Django 4.2.7 on 2025-07-24 14:34

import apps.documents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rhp', 'Red Herring Prospectus'), ('drhp', 'Draft Red Herring Prospectus'), ('prospectus', 'Final Prospectus'), ('addendum', 'Addendum'), ('corrigendum', 'Corrigendum'), ('other', 'Other Document')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Allowed formats: PDF, DOC, DOCX', upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('original_filename', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the document is publicly accessible')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipos.ipo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('ipo', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Download Log',
                'verbose_name_plural': 'Document Download Logs',
                'db_table': 'document_download_logs',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
